### ISSUE TITLE
Test::Output fails to install on Windows without --force-test

### ISSUE THREAD

**Issue by jaguart** [raku-community-modules/Test-Output#9]
```
===> Testing: Test::Output:ver<1.001004>
Testing: Test::Output:ver<1.001004>
[Test::Output] # Failed test 'verbosity testing output-like'
[Test::Output] # at C:\Users\jeff\.zef\store\Test-Output-master\049004EC0BA8F4474254A9BB9E26FE521EEEA096\lib\Test\Output.pm6 (Test::Output) line 92
[Test::Output] # expected a match with: /42.+warning '!' "\n" warning.+After/
[Test::Output] #                   got: "42\r\nwarning!\r\nwarning!\r\nAfter warning\r\n"
[Test::Output] # Failed test 'stdout-like on line 1'
[Test::Output] # at C:\Users\jeff\.zef\store\Test-Output-master\049004EC0BA8F4474254A9BB9E26FE521EEEA096\lib\Test\Output.pm6 (Test::Output) line 92
[Test::Output] # expected a match with: /42 "\n" warning '!'/
[Test::Output] #                   got: "42\r\nwarning!\r\nAfter warning\r\n"
[Test::Output] # You failed 2 tests of 18
===> Testing [FAIL]: Test::Output:ver<1.001004>
```
I guess that the tests need an update to cope with the platform NL

**Comment by sdondley** [comment]
Confirmed. Using windows 11. But I'm getting a different error:

  zef install Test::Output
===> Searching for: Test::Output
===> Testing: Test::Output:ver<1.001004>
[Test::Output] ===SORRY!=== Error while compiling C:\Users\sdond\.zef\tmp\Test%3A%3AOutput%3Aver%3C1.001004%3E%3Aauth%3Cgithub%3Araku-community-modules%3E.tar.gz\Test-Output-master/t\00-use.t
[Test::Output] Failed to open file C:\Users\sdond\.zef\tmp\Test%3A%3AOutput%3Aver%3C1.001004%3E%3Aauth%3Cgithub%3Araku-community-modules%3E.tar.gz\Test-Output-master\.precomp\BE04B1FADFC312E3411CB403B43E629B7AED3ADC\27\27F410113BBD23B298581F9F713FBCFB39C1584E.repo-id.2YKZ9SRUPW9RWSWT2ADKOPZGM.tmp: No such file or directory
[Test::Output] at C:\Users\sdond\.zef\tmp\Test%3A%3AOutput%3Aver%3C1.001004%3E%3Aauth%3Cgithub%3Araku-community-modules%3E.tar.gz\Test-Output-master/t\00-use.t:4
[Test::Output] Actually thrown at:
[Test::Output]   in any statement_control at C:\Program Files\Rakudo\bin\..\share\perl6\lib/Perl6/Grammar.moarvm line 1
[Test::Output] ===SORRY!=== Error while compiling C:\Users\sdond\.zef\tmp\Test%3A%3AOutput%3Aver%3C1.001004%3E%3Aauth%3Cgithub%3Araku-community-modules%3E.tar.gz\Test-Output-master/t\01-capture.t
[Test::Output] Failed to open file C:\Users\sdond\.zef\tmp\Test%3A%3AOutput%3Aver%3C1.001004%3E%3Aauth%3Cgithub%3Araku-community-modules%3E.tar.gz\Test-Output-master\.precomp\BE04B1FADFC312E3411CB403B43E629B7AED3ADC\27\27F410113BBD23B298581F9F713FBCFB39C1584E.repo-id.17SSVAMQ8RX8DQEVOPG4PQ5HD.tmp: No such file or directory
[Test::Output] at C:\Users\sdond\.zef\tmp\Test%3A%3AOutput%3Aver%3C1.001004%3E%3Aauth%3Cgithub%3Araku-community-modules%3E.tar.gz\Test-Output-master/t\01-capture.t:3
[Test::Output] Actually thrown at:
[Test::Output]   in any statement_control at C:\Program Files\Rakudo\bin\..\share\perl6\lib/Perl6/Grammar.moarvm line 1
===> Testing [FAIL]: Test::Output:ver<1.001004>
Aborting due to test failure: Test::Output:ver<1.001004> (use --force-test to override)

**Comment by sdondley** [comment]
OK, the problem I'm having is a known issue with zef on windows: https://github.com/ugexe/zef/issues/452

After adding `--/rea` switch to `zef install` command, I can now see the same error with newlines.

**Comment by sdondley** [comment]
This is fixed. Should be closed now.
